# Generated by iptables-save v1.6.0 on Thu Jan
# Completed on Thu Jan 19 02:27:00 2017
sudo iptables-restore ~/iptables.txt
sysctl net.ipv4.ip_forward=1
create_ap -n wlp0s26u1u5u4 viscount 1234567890

